#!/bin/bash

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`
createDBFolder(){
    db="DBMS"
    if [[ -d $db ]];then
    clear
    else
    mkdir DBMS
    fi
    clear
   echo "${green}========================"
   echo "        Welcome         "
   echo "========================${reset}"
    sleep 1
. ./DBmenu
}

createDBFolder

# checkExist(){

# if [[ $1 = "dir" ]];then

#         if [[ -d  $2 ]];then
#         echo $2
#         else

#         echo dir not found
#         fi
# elif [[ $1 = "file" ]];then
#         if [[ -f  $2 ]] ;then
#             echo $2
#             else

#             echo file not found
#             fi
# fi            
    
# }

# # checkExist dir DB
