#!/bin/bash
# name="1 #$  true no& nn4()-sad "
# name="da"
# # echo $name
# # for i in $name
# # do 
# if [[ $name =~ ^[a-zA-Z]{1,}$ ]];then
#     echo $name
# fi
# # done


# for i in $(ls ./DBMS)
# do 

# # echo $i
# if [[ $i == "n" ]];then
# echo $i
# fi
# # done
# f1="/etc/passwd"
# f2="/etc/shadow"
# while read line ;do
# # echo ${f1:$line:1}
# cut -d : -f1,3-7,9
# done <<( $f1 $f2)
# arr=[]
		array=(`awk -F":" '{if (NR>=3) print $3}' ./DBMS/user/meta_table/meta`)
        datatype=(`awk -F":" '{if (NR>=3) print $4}' ./DBMS/user/meta_table/meta`)
# echo "${array[*]}" #elements
pk=(`awk -F":" '{print $1}' ./DBMS/user/table`)
echo "${pk[*]}" #elements

echo "${#pk[*]}" #size

# for (( k = 0 ; k < $size; k++ ));do
#     echo ${array[$k]}
#     echo "${datatype[$k]}"
# done

# size="${#array[*]}"
# for (( k = 0 ; k < $size; k++ ));do
#     echo ${array[$k]}
#     echo "${datatype[$k]}"
# done


dump(){
    echo $1
}


# dump ${array[1]}
# vaildInput() {
#     stat=0
#     if [[ $1 = "int" ]];then
#         while [[ $stat =0 ]];do
#             if  [[ $1 =~ ^[1-9] ]];then
#                 stat=1
#             else
#             echo "${red}invaild input only numbers {1,9}${reset}"
            
#             Main
#             fi    
#         done 
#     elif [[ $1 = "str" ]];then
#           while [[ $stat =0 ]];do
#             if  [[ $1 =~ ^[a-zA-Z]{1,}$ ]];then
#                 stat=1
#             else
#             echo "${red}invaild input only string ${reset}"
#             Main
#             fi    
#         done

#     fi

# }



# awk -F":" '{print $1}' ./DBMS/uu/ew
# checkColName(){
# colname=$1

#     st=0
#     while [[ $st = 0 ]]; do
#         if ! [[ $colname =~ ^[a-zA-Z]{1,}$ ]];then
#         echo "${red}not vaild ${reset}"
#         read -p "enter colname : " colname
#         else
#         st=1
#         fi
#     done
#     echo $st
# }

# read -p "enter colname : " colname
# checkColName  $colname

# ====================================
#  db menu
# =========================================
#   +    Create Database 
#   +    List Databases
#   +    Connect To Databases
#   +    Drop Database
#   +    Exit from Databse
# =============================
# table menu
# =============================
#   +    Create Table
#   +    List Tables
#   +    Drop Table
#        Insert into Table
#        Select From Table => 1-select all 2-select by col 3-select by row
#        Delete From Table
#        Update Table
#   +    Return to main menu